apiVersion: backup.appuio.ch/v1alpha1
kind: Backup
metadata:
  name: backup-test
spec:
  keepJobs: 4
  promURL: http://minio:9000
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
      endpoint: http://minio:9000
      bucket: backups
      accessKeyIDSecretRef:
        name: backup-credentials
        key: username
      secretAccessKeySecretRef:
        name: backup-credentials
        key: password
