apiVersion: backup.appuio.ch/v1alpha1
kind: Backup
metadata:
  name: backup-test
spec:
  keepJobs: 4
  promURL: https://sos-ch-gva-2.exo.io
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
      endpoint: https://sos-ch-gva-2.exo.io
      bucket: backups-getting-started-repo
      accessKeyIDSecretRef:
        name: backup-credentials
        key: username.txt
      secretAccessKeySecretRef:
        name: backup-credentials
        key: password.txt
