apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  annotations:
    # k8up.syn.tools/backup: "true"
    appuio.ch/backup: "true"
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
