apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress
  type: LoadBalancer
