apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  labels:
    app: wordpress
spec:
  # https://github.com/rancher/local-path-provisioner/issues/70
  # Rancher's local path provisioner only supports the RWO access mode
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
