apiVersion: backup.appuio.ch/v1alpha1
kind: Restore
metadata:
  name: restore-mariadb
spec:
  snapshot: SNAPSHOT_ID
  restoreMethod:
    folder:
      claimName: mariadb-pvc
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
      endpoint: http://minio:9000
      bucket: backups
      accessKeyIDSecretRef:
        name: backup-credentials
        key: username
      secretAccessKeySecretRef:
        name: backup-credentials
        key: password
