apiVersion: v1
kind: Service
metadata:
  name: minio-api
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
spec:
  type: LoadBalancer
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
  selector:
    app: minio
