apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
  namespace: default
type: Opaque
data:
  username: bWluaW8=          # echo -n "minio" | base64
  password: bWluaW8xMjM=      # echo -n "minio123" | base64
